packages:
  - name: catscan
    environment:
      SPACES_KEY: "${SPACES_KEY}"
      SPACES_SECRET: "${SPACES_SECRET}"
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASS: '${MYSQL_PASS}'
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_PORT: '${MYSQL_PORT}'
      MYSQL_DB: '${MYSQL_DB}'
    functions:
      - name: cleanup
        web: false
        runtime: 'python:3.11'
        triggers:
          - name: 'every hour'
            sourceType: scheduler
            sourceDetails:
              cron: '0 * * * *'
      - name: word
        web: true
        runtime: 'python:3.11'
        limits:
          timeout: 15000
      - name: conferences
        web: true
        runtime: 'python:3.11'
      - name: latex
        web: true
        runtime: 'go:1.20'